### ISSUE TITLE
Question about data resolution

### ISSUE THREAD

**Issue by weifangliu** [ma-compbio/Fast-Higashi#4]
Hello, I was wondering if Fast-Higashi can be used with 10kb scHi-C data for imputation?

**Comment by ruochiz** [comment]
Hi,

Thanks for your interest. The partial rwr part of the Fast-Higashi can in principle be used as the imputation for 10kb map. But since imputation is not one of the initial goal of Fast-Higashi and the code is written in a way to squeeze large scHi-C dataset into GPU, in order to achieve 10kb imputation, the `off_diag` param needs to be something small, like 100 (so impute within 1Mb distance), definitely not a whole genome imputation.
